apiVersion: v1
kind: Pod
metadata:
  name: HF_SM_8
  namespace: default
spec:
  containers:
    - name: container1
      image: nginx
      resources:
        limits:
          memory: '10Mi'
          cpu: 1

